commit/commit.py

- Imported additional necessary modules for functionality
- Modified path handling to enhance module compatibility
- Adjusted imports for clarity and maintenance

refactor: Update import paths in commit module

---

ask-code/ask-code.py
commit/commit.py

1. format cost output in ask-code
2. handle Chinese file name
3. add limit to diff length in commit workflow

Add limit to generate commit message

---

commit/commit.py

Parse response content with markdown block. In other llm model response, commit message is in a markdown block.

feat: Add function to extract Markdown code blocks

---

.github/workflows/sync-to-gitlab.yml

- Modify git rebase command to use -Xours strategy option

fix: Resolve sync error with git rebase

---

unit_tests/assistants/directory_structure/base.py
unit_tests/assistants/directory_structure/relevant_file_finder.py
unit_tests/command.yml
unit_tests/propose_test.py
unit_tests/tools/tiktoken_util.py
unit_tests/write_tests.py

Reverts devchat-ai/workflows#38
重做 #37 ，需等正确时机合并
-----
此PR合并到 minimax_main 后分支暂时不要删

Revert "Revert "/unit_tests switch to devchat env""

---

libs/llm_api/minimax_chat.py
libs/llm_api/openai.py

参考示例：
```
import sys
import os
home = os.path.expanduser("~")
org_libs_path = os.path.join(home, ".chat", "workflows", "org", "libs")
sys_libs_path = os.path.join(home, ".chat", "workflows", "sys", "libs")
sys.path.append(org_libs_path)
sys.path.append(sys_libs_path)
from llm_api import chat_completion_stream, chat_completion_no_stream_return_json  # noqa: E402
def main():
print("start test ...", end="\n\n", flush=True)
model = os.environ.get("LLM_MODEL", "gpt-3.5-turbo-1106")
task1 = "hello"
response = chat_completion_stream([{"role": "user", "content": task1}] , {"model": model})
print(response['content'], end="\n\n")
response = chat_completion_stream([{"role": "user", "content": task1}] , {"model": model}, stream_out=True)
print(response['content'], end="\n\n")
task2 = …
```

support minimax llm

---

libs/llm_api/minimax_chat.py
libs/llm_api/openai.py

update minimax llm api

---

commit/commit.py

This PR introduces better error messages and warnings to improve user interaction when there are no files to commit.
Changes include:
- Updated error messages for a situation where no files are available to commit.
- Enhanced the commit aborted message to be more explicit and user-friendly.
- Aimed at providing a smoother experience by providing helpful and timely warnings during the workflow.
Closes https://github.com/devchat-ai/devchat/issues/188 as this addresses the reported UX concerns.

Improve user interaction for commit errors

---

unit_tests/main.py
unit_tests/prompts.py
unit_tests/propose_test.py

Using the triangle function as an example.
Before:
After:

feat: maintain a balance between happy paths and edge cases

---

commit/command.yml
commit/commit.py
commit/zh/command.yml
libs/llm_api/openai.py
libs/llm_api/pipeline.py

This pull request addresses the context overflow error that was causing the second commit submission to fail when generating Chinese commit messages.
Changes made:
- Set the language code to "en" in `commit/command.yml`.
- Modified `commit/commit.py` to handle errors related to the model's maximum context length.
- Updated `commit/zh/command.yml` with "zh" language code.
- Adjusted `libs/llm_api/openai.py` to bypass the token limit error.
By merging this pull request, we should see the issue resolved and both English and Chinese commit submissions working as expected.
Closes devchat-ai/devchat#189

Fix context overflow issue causing commit submission failure

---

unit_tests/openai_util.py

This pull request addresses the bug where the `create_chat_completion_content` function was resulting in empty content. A fix has been implemented to ensure that the output is correctly formatted as JSON.
- Ensure proper JSON formatting in response content of `create_chat_completion_content` function.

Fix empty content issue in create_chat_completion_content function

---

libs/llm_api/openai.py
libs/llm_api/pipeline.py

This pull request includes a series of updates aimed at improving the code quality and exception handling within our codebase.
- Refactor pipeline imports to enhance readability and maintainability.
- Update the exception handling in `llm_api/openai.py` to ensure that the response is properly formatted as a JSON object.
These refinements should improve the robustness of our application's error handling mechanisms and make the import structure more straightforward.

Refactor Pipeline Imports and Update Exception Handling in LLM API

---

libs/llm_api/__init__.py
libs/llm_api/chat.py
libs/llm_api/memory/base.py
libs/llm_api/memory/fixsize_memory.py
libs/llm_api/openai.py
libs/llm_api/pipeline.py
libs/llm_api/text_confirm.py
libs/llm_api/tools_call.py

This pull request introduces a series of enhancements and refactors aimed at improving the LLM API's functionality and maintainability.
**New Features:**
- New chat functionalities and text confirmations for improved user interaction within the LLM API (3185f1c).
- A new `tools_call.py` file that brings additional functionalities and decorators to handle tool and function schemas (8b57912).
**Optimizations:**
- Overhauled the handling of function calls with a more efficient process and better integration (76c7663).
**Refactorings:**
- Restructured the `llm_api` module and package imports for better code organization and readability (c6f7e2a, 1570490).
- Refined error handling mechanisms in `openai.py` (1aa46e4).
**Chores:**
- Introduced a memory module to enhance the statefulness of the …

Enhance LLM API with New Features, Refactorings, and Optimizations

---

docstring/main.py

This PR addresses a bug where the large model would drop original function implementations during the process of adding docstrings, as reported in issue [#290](https://github.com/devchat-ai/devchat/issues/290). I have made changes to optimize the docstring generation process, ensuring that the original function code is retained and minimally interfered with by the visible code context.
- Visible code references are now removed during the generation of docstrings.
- Large functions now maintain their original code when docstrings are added.
With these changes, the expected behavior should be met where the large model will output both the original function implementation and the newly added docstrings with no loss of functionality.
Closes devchat-ai/devchat#290.

Fix Issue with Large Models Dropping Function Code When Adding Docstrings

---

configuration.toml

This PR introduces a new `configuration.toml` file to the workflows plugin, aimed at displaying recommended workflows as proposed in issue [#304](https://github.com/devchat-ai/devchat/issues/304). The file has been populated with an initial set of recommended workflows and is formatted to be properly readable using a provided Python script to verify its correctness.
**Key Changes:**
- A `configuration.toml` file was added containing the recommended workflows.
- The file's format has been verified to be correct using a Python script for reading and printing out the workflow configuration data.
close https://github.com/devchat-ai/devchat/issues/304
The integrity of the configuration file was confirmed by reading its content with the following Python script:
```python
import toml
def …
```

Add Configuration File for Workflow Recommendations

---

configuration.toml

enhancement
___
- Updated the `workflows` list in `configuration.toml` to include "comments" and "fix", and removed "comment". This enhances the workflow capabilities by distinguishing between singular and plural forms of comments and adding a fix workflow.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>configuration.toml</strong><dd><code>Update Workflows in Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
configuration.toml
<li>Added "comments" and "fix" to the workflows list.<br> <li> …

feat: add fix/comments workflow

---

comments/command.yml
comments/main.py
docstring/command.yml
docstring/main.py
explain/command.yml
explain/explain.py
fix/command.yml
fix/main.py
refactor/rewrite.py

This pull request addresses a couple of user interaction improvements with our application:
1. When no code is selected, we now display the content of the `README.md` file as a default view, enhancing the user experience by providing immediate guidance on how to use the tool.
2. Improved the selection validation logic across various modules to ensure that non-selections (where the start and end range of a selection are identical) are correctly identified, preventing errors related to the absence of text selection.
These changes provide a more intuitive user experience by eliminating confusion around command requirements and selection validation.
Changes include:
- Display `README.md` by default when no text is selected.
- Modified command and main modules to support the new feature.
- …

Enhance Non-Selection Behavior and Validate Selection Across Modules

---

commit/command.yml
commit/commit.py
commit/zh/command.yml

This pull request introduces changes to support Chinese language in commit workflow outputs. It addresses the feature request outlined in issue devchat-ai/devchat#315 by implementing automatic language detection and providing bilingual messages based on the user's language configuration.
Changes include:
- Language detection feature to streamline workflow outputs in Chinese or English, based on user preference.
- Bilingual messages for enhanced accessibility to our Chinese-speaking developers.
- Removal of the redundant Chinese command file for a more efficient approach.
close devchat-ai/devchat#315
___
enhancement
___
- Implemented bilingual (English and Chinese) support in workflow scripts based on IDE language settings, enhancing accessibility for Chinese-speaking developers.
- Removed …

Implement Chinese Language Support for Workflow Outputs

---

comments/README.md
docstring/README.md
explain/README.md
fix/README.md
refactor/README.md
unit_tests/README.md

This pull request introduces several updates to enhance the documentation and user interface:
- Updated the workflow guides to provide more clarity and better explanations, which include general refactors, fixes, comments, docstrings, and workflow definitions.
- Adjusted the spacing between images to improve visual separation and readability.
The improvements to the guides should result in a more straightforward and intuitive understanding for users to follow best practices and contribute effectively.
List of changes:
- Add spacing to increase the distance between images.
- Improve refactor workflow guide.
- Improve explain workflow guide.
- Improve fix workflow guide.
- Improve comments workflow guide.
- Improve docstring workflow guide.
These modifications seek to enhance the quality of …

Improve Workflow Guides and Image Spacing Adjustment

---

comments/main.py
docstring/main.py
refactor/names/command.yml
refactor/names/main.py
refactor/rewrite.py

This pull request improves the readability of code and enhances error handling in command.yml and rewrite.py files.
No associated issue to close.

Refactor command.yml and rewrite.py for Enhanced Readability and Error Handling
